#!/usr/bin/python
#-*-coding:utf-8-*-
import os

# kullanımı şekli konsoldan şu şekilde yapmanız yeterli
# yourname@ubuntu:~$ sudo python dns_IP.py

metin = "# Generated by NetworkManager\
\nnameserver " + "8.8.8.8"+\
"\nnameserver "  + "8.8.4.4"
yaz = open("/etc/resolv.conf", "w")
yaz.write(metin)
yaz.close()
print "© Copyright gdemir"
