#!/usr/bin/python
#-*-coding:utf-8-*-
import os

# kullanımı şekli konsoldan şu şekilde yapmanız yeterli
# yourname@ubuntu:~$ sudo python orjinaldns_IP.py

metin = "# Generated by NetworkManager\
\n\nnameserver " + "192.168.2.1"
yaz = open("/etc/resolv.conf", "w")
yaz.write(metin)
yaz.close()
print "© Copyright gdemir"
