#!/bin/sh
sudo aptitude install mysql-server mysql-client
sudo ps aux | grep mysqld
sudo aptitude install apache2
sudo ps aux | grep apache
sudo aptitude install php5 libapache2-mod-php5
sudo /etc/init.d/apache2 restart
sudo chmod 777 -R /var/www
echo "<?php
phpinfo();
?>" > /var/www/info.php
sudo /etc/init.d/apache2 restart
sudo aptitude install php5-mysql php5-curl php5-gd php5-idn php-pear php5-imagick php5-imap php5-mcrypt php5-memcache php5-mhash php5-ming php5-ps php5-pspell php5-recode php5-snmp php5-sqlite php5-tidy php5-xmlrpc php5-xsl php5-json
sudo /etc/init.d/apache2 restart
sudo aptitude install phpmyadmin
